::msgcat::mcset ru_ru.koi8-r "Initializing..." "Се Иницијализира..."

::msgcat::mcset ru_ru.koi8-r "Components read:" "Читање на компонентите:"

::msgcat::mcset ru_ru.koi8-r "Can't open the file" "Датотеката не може да се отвори"

::msgcat::mcset ru_ru.koi8-r "Close" "Затвори го"

::msgcat::mcset ru_ru.koi8-r "Exit" "Излез"

::msgcat::mcset ru_ru.koi8-r "Sample Rate" "Нормална Стапка"

::msgcat::mcset ru_ru.koi8-r "Sample Encoding" "Нормално Кодирање"

::msgcat::mcset ru_ru.koi8-r "Channels" "Канали"

::msgcat::mcset ru_ru.koi8-r "Mono" "Моно"

::msgcat::mcset ru_ru.koi8-r "Stereo" "Стерео"

::msgcat::mcset ru_ru.koi8-r "Associate extension" "Поврзани типови"

::msgcat::mcset ru_ru.koi8-r "with these values" " "Со овие вредности"

::msgcat::mcset ru_ru.koi8-r "(click to cancel)" "(Кликни за откажување)"

::msgcat::mcset ru_ru.koi8-r "done." "Завршено."

::msgcat::mcset ru_ru.koi8-r "Interrupted" "Прекинато"

::msgcat::mcset ru_ru.koi8-r "Decibels" "Децибели"

::msgcat::mcset ru_ru.koi8-r "Amplify by:" "Засили го за:"

::msgcat::mcset ru_ru.koi8-r "Normalize" "Нормализирај"

::msgcat::mcset ru_ru.koi8-r "Normalize to:" "Нормализирај во:"

::msgcat::mcset ru_ru.koi8-r "Normalize all channels equally" "Нормализирај ги сите канали подеднакво"

::msgcat::mcset ru_ru.koi8-r "Echo" "Ехо"

::msgcat::mcset ru_ru.koi8-r "In" "Внатре"

::msgcat::mcset ru_ru.koi8-r "Out" "Надвор"

::msgcat::mcset ru_ru.koi8-r "Read Offset (bytes)" "Читај урамнотежено (битови)"

::msgcat::mcset ru_ru.koi8-r "Byte Order" "Ред на Битови"

::msgcat::mcset ru_ru.koi8-r "Converting sample rate..." "Ковертирање во нормална стапка... "

::msgcat::mcset ru_ru.koi8-r "Converting sample encoding format..." "Конвертирање во обичен формат..."

::msgcat::mcset ru_ru.koi8-r "Converting number of channels..." "Претворање на бројот на канали..."

::msgcat::mcset ru_ru.koi8-r "Computing pitch..." "Процесирање на интензитетот..."

::msgcat::mcset ru_ru.koi8-r "Reading sound..." "Вчитување на звукот..."

::msgcat::mcset ru_ru.koi8-r "Writing sound..." "Запишување на звукот..."

::msgcat::mcset ru_ru.koi8-r "Precomputing waveform..." "Препроцесирање на wave формата" 

::msgcat::mcset ru_ru.koi8-r "Reversing sound..." "Враќање назад на звукот..." 

::msgcat::mcset ru_ru.koi8-r "Filtering sound..." "Филтрирање на звукот..."

::msgcat::mcset ru_ru.koi8-r "Interpret Raw File As" "Интерпретирај Raw фајл како" 

::msgcat::mcset ru_ru.koi8-r "You have unsaved changes." "Имате неснимени промени."

::msgcat::mcset ru_ru.koi8-r "Do you really want to exit?" "Дали сакате да излезете?"

::msgcat::mcset ru_ru.koi8-r "File type" "Тип на датотека"

::msgcat::mcset ru_ru.koi8-r "Associate" "Поврзи ги"

::msgcat::mcset ru_ru.koi8-r "Make default" "Постави го Default"

::msgcat::mcset ru_ru.koi8-r "Use DDE" "Користи DDE"

::msgcat::mcset ru_ru.koi8-r "Help" "Помош"

::msgcat::mcset ru_ru.koi8-r "About WaveSurfer" "п WaveSurfer"

::msgcat::mcset ru_ru.koi8-r "Manual" "Упатство"

::msgcat::mcset ru_ru.koi8-r "Convert..." 

::msgcat::mcset ru_ru.koi8-r "Amplify..." "Засили го..."

::msgcat::mcset ru_ru.koi8-r "Normalize..." "Нормализирај го..."

::msgcat::mcset ru_ru.koi8-r "Echo..." "Ехо..."

::msgcat::mcset ru_ru.koi8-r "Mix Channels..." "Измешај ги каналите..."

::msgcat::mcset ru_ru.koi8-r "Invert" "Инвертирај" 

::msgcat::mcset ru_ru.koi8-r "Reverse"
"Пушти назад"
::msgcat::mcset ru_ru.koi8-r "Silence" "Тишина"

::msgcat::mcset ru_ru.koi8-r "Save" "Сними"

::msgcat::mcset ru_ru.koi8-r "Print..." "Печати..."

::msgcat::mcset ru_ru.koi8-r "Save As..." "Сними како..."

::msgcat::mcset ru_ru.koi8-r "Save Selection..." "Сними го селектираното..."

::msgcat::mcset ru_ru.koi8-r "Undo" "Врати"

::msgcat::mcset ru_ru.koi8-r "Cut" "Исечи"

::msgcat::mcset ru_ru.koi8-r "Copy" "Копирај"

::msgcat::mcset ru_ru.koi8-r "Paste" "Залепи"

::msgcat::mcset ru_ru.koi8-r "Select All" "Селектирај се"

::msgcat::mcset ru_ru.koi8-r "Play whole selection:" "Пушти ја селекцијата:"

::msgcat::mcset ru_ru.koi8-r "Play whole sound:" "Пушти го целиот звук:"

::msgcat::mcset ru_ru.koi8-r "Play at cursor:" "Почни од Курсерот:"

::msgcat::mcset ru_ru.koi8-r "Toggle play/pause:" "Пушти/Пауза:"

::msgcat::mcset ru_ru.koi8-r "Defined file extension types:" "Дефинирани типови на датотеки:"

::msgcat::mcset ru_ru.koi8-r "Associate file types..." "Вклчени типови на датотеки"

::msgcat::mcset ru_ru.koi8-r "Zero Cross Adjust" "Подеси над нула"

::msgcat::mcset ru_ru.koi8-r "Zero Cross Adjust:" "Подеси над нула:"
::msgcat::mcset ru_ru.koi8-r "Normalize cancelled" "Нормализацијата е откажана"

::msgcat::mcset ru_ru.koi8-r "New channel" "Нов канал"

::msgcat::mcset ru_ru.koi8-r "New..." "Нов..."

::msgcat::mcset ru_ru.koi8-r "Open..." "Отвори..."

::msgcat::mcset ru_ru.koi8-r "Preferences..." "Подесувања..."

::msgcat::mcset ru_ru.koi8-r "Show Console" "Прикажи ја Конзолата"

::msgcat::mcset ru_ru.koi8-r "Mixer..." "Миксер..."

::msgcat::mcset ru_ru.koi8-r "Edit" "Уреди"

::msgcat::mcset ru_ru.koi8-r "File" "Датотека"

::msgcat::mcset ru_ru.koi8-r "Transform" "Трансформации"

::msgcat::mcset ru_ru.koi8-r "Apply Configuration..." "Примени ја Конфигурацијата.."

::msgcat::mcset ru_ru.koi8-r "Save Configuration..." "Сними ја Конфигурацијата"

::msgcat::mcset ru_ru.koi8-r "Properties..." "Параметри..."

::msgcat::mcset ru_ru.koi8-r "Properties:" "Параметри:"

::msgcat::mcset ru_ru.koi8-r "Zoom to Selection" "Зголеми ја Селекцијата"

::msgcat::mcset ru_ru.koi8-r "Delete Pane" "Избриши го платното  "

::msgcat::mcset ru_ru.koi8-r "Create Pane" "Креирај платно "

::msgcat::mcset ru_ru.koi8-r "Input device:" "Внатрешна единица:"

::msgcat::mcset ru_ru.koi8-r "Output device:" "Надворешна единица:"

::msgcat::mcset ru_ru.koi8-r "Cancel" "Откажи"

::msgcat::mcset ru_ru.koi8-r "Apply" "Примени"

::msgcat::mcset ru_ru.koi8-r "Selection color:" "Селекција на бои:"

::msgcat::mcset ru_ru.koi8-r "Choose..." "Избери..."

::msgcat::mcset ru_ru.koi8-r "Selection frame color:" "Избери боја на рамката:"

::msgcat::mcset ru_ru.koi8-r "Y-axis color:" "Боја на Y-Оската:"

::msgcat::mcset ru_ru.koi8-r "Y-axis font:" "Фонт на Y-Оската:"

::msgcat::mcset ru_ru.koi8-r "Background color:" "Боја на позадината:"

::msgcat::mcset ru_ru.koi8-r "Pane height:" "Висина на платното:"

::msgcat::mcset ru_ru.koi8-r "Pixels per second:" "Пиксели во секунда:"

::msgcat::mcset ru_ru.koi8-r "Choose configuration" "Избери конфигурација"

::msgcat::mcset ru_ru.koi8-r "pixels" "пиксели"

::msgcat::mcset ru_ru.koi8-r "Pane scrolled" "Лизгачко Платно"

::msgcat::mcset ru_ru.koi8-r "Pane scroll height:" "Должина на лизгачкото платно:"

::msgcat::mcset ru_ru.koi8-r "Display selection length" "Прикажи ја должината на селекцијата"

::msgcat::mcset ru_ru.koi8-r "Sound storage:" "Складирање на звукот:"

::msgcat::mcset ru_ru.koi8-r "keep on disk" "Зачувај на диск"

::msgcat::mcset ru_ru.koi8-r "load into memory" "Вчитај во меморија"

::msgcat::mcset ru_ru.koi8-r "Temporary directory:" "Привмремен директориум:"

::msgcat::mcset ru_ru.koi8-r "Print command:" "Испечати ја командата:"

::msgcat::mcset ru_ru.koi8-r "Preview command:" "Прикажи ја командата:"

::msgcat::mcset ru_ru.koi8-r "Record time limit:" "Граница на времето за снимање:"

::msgcat::mcset ru_ru.koi8-r "s" "У"

::msgcat::mcset ru_ru.koi8-r "Icons:" "Икони:"

::msgcat::mcset ru_ru.koi8-r "Do not query for configuration" "Не побарувај конфигурација "

::msgcat::mcset ru_ru.koi8-r "Max zoom-in:" "Максимален Зум-ин:"

::msgcat::mcset ru_ru.koi8-r "Automatic scroll during playback" "Автоматско листање за време на плејбекот"

::msgcat::mcset ru_ru.koi8-r  "Installed plug-ins:" "Инсталирани додатоци:"

::msgcat::mcset ru_ru.koi8-r "Description:" "Опис:"

::msgcat::mcset ru_ru.koi8-r "Save to PS-file:" "Сними го во PS-датотека:"

::msgcat::mcset ru_ru.koi8-r "Save" "Сними го"

::msgcat::mcset ru_ru.koi8-r "Printing..." "Се печати..."

::msgcat::mcset ru_ru.koi8-r "Do you really want to close?" "Дали навистина сакате да го затворите?"
